### ISSUE TITLE
Nothing happen

### ISSUE THREAD

**Issue by cowboygary** [Adlink-ROS/neuron-bsp-ros-example#1]
Hi @cwyark 
I'm using Roscube-I. 

After I run roscore and rosrun uron-bsp-gpio neuron-bsp-gpio_node
Nothing happen.

Can you guide me on this?

**Comment by cowboygary** [comment]
I got this error:

set pin direction failed

**Comment by cwyark** [comment]
@cowboygary could you try your program as a root user?  hardware access need root permission.

**Comment by cowboygary** [comment]
Yes @cwyark 

I sudo su already.
Still got the set pin direction failed

**Comment by cowboygary** [comment]
Hi @cwyark 

I change the pin number to 127 then I get the pin value.
But when I push my button, the value is not changing.
I wire my button using pull-down resistor method. (Roscube-I : pin 7,37 and 43)

Do I miss anything?
